### ISSUE TITLE
Error opening terminal when attempting to use htop

### ISSUE THREAD

**Issue by aussiDavid** [ydkn/capistrano-interactive#1]
When I try to run the following task I get an error:

```
 desc 'Runs htop to monitor the server'
  task :monitor do
    on primary(:app) do
      interact(:htop)
    end
  end
```

...
`Error opening terminal: unknown.`

**Comment by ydkn** [comment]
Sorry for the late answer.
I dropped support for this gem in favor of contributing to https://github.com/afeld/sshkit-interactive.

A quick check running htop with _sshkit-interactive_ worked in my setup. Can you please try with _sshkit-interactive_.

I'm closing this issue, if it still doesn't work for you please create a new issue at https://github.com/afeld/sshkit-interactive/issues.
This time I promise to get back to you much sooner.
